PREFIX c:<http://s.opencalais.com/1/pred/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?name ?importance ?resourceEntity ?socialTag
    WHERE   {
    {
		?descriptionA c:docId ?docId .

		?descriptionA c:exact ?exact .
		?descriptionB c:docId ?docId .
		?descriptionB c:relevance ?relevance .

    ?resourceEntity c:docId ?docId .
    ?resourceEntity c:importance ?importance .
    ?resourceEntity c:name ?name .
    ?resourceEntity c:originalValue ?originalValue .
    #TODO: I assume that is socialTag object is the subject of the linked data
    ?resourceEntity c:socialtag ?socialTag .
    ?resourceEntity rdf:type <http://s.opencalais.com/1/type/tag/SocialTag>

    }

    }

    	ORDER BY DESC(?relevance)

