
package com.Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "calais", targetNamespace = "http://clearforest.com/", wsdlLocation = "http://api.opencalais.com/enlighten/?wsdl")
public class Calais
    extends Service
{

    private final static URL CALAIS_WSDL_LOCATION;
    private final static WebServiceException CALAIS_EXCEPTION;
    private final static QName CALAIS_QNAME = new QName("http://clearforest.com/", "calais");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://api.opencalais.com/enlighten/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALAIS_WSDL_LOCATION = url;
        CALAIS_EXCEPTION = e;
    }

    public Calais() {
        super(__getWsdlLocation(), CALAIS_QNAME);
    }

    public Calais(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALAIS_QNAME, features);
    }

    public Calais(URL wsdlLocation) {
        super(wsdlLocation, CALAIS_QNAME);
    }

    public Calais(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALAIS_QNAME, features);
    }

    public Calais(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Calais(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalaisSoap
     */
    @WebEndpoint(name = "calaisSoap")
    public CalaisSoap getCalaisSoap() {
        return super.getPort(new QName("http://clearforest.com/", "calaisSoap"), CalaisSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalaisSoap
     */
    @WebEndpoint(name = "calaisSoap")
    public CalaisSoap getCalaisSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://clearforest.com/", "calaisSoap"), CalaisSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALAIS_EXCEPTION!= null) {
            throw CALAIS_EXCEPTION;
        }
        return CALAIS_WSDL_LOCATION;
    }

}
